schema_version = "1.0.0"

id = "mandelbulb"
version = "1.0.1"

name = "Mandelbulb Generator"
tagline = "Mandelbulb and Julia Fractal Generator"

maintainer = "Suussonic"

type = "add-on"

website = "https://github.com/Suussonic/Mandelbulb"

tags = [
    "Add Mesh",
    "Modeling",
]

blender_version_min = "5.1.0"

license = [
    "SPDX:GPL-3.0-or-later",
]

[build]
paths_exclude_pattern = [
    "__pycache__/",
    "*.pyc",
    "*.pyo",
    ".git/",
    ".github/",
    ".vscode/",
    "tests/",
]